<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <EnablePackageValidation>true</EnablePackageValidation>
    <!-- This package won't produce a stable version -->
    <SuppressFinalPackageVersion>true</SuppressFinalPackageVersion>
    <PreReleaseVersionLabel>preview.1</PreReleaseVersionLabel>
  </PropertyGroup>

  <PropertyGroup Label="Package Information">
    <Description>Aspire integration for Microsoft.AspNetCore.SystemWebAdapters to support incremental migration scenarios.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.AspNetCore.SystemWebAdapters.CoreServices\Microsoft.AspNetCore.SystemWebAdapters.CoreServices.csproj" />
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Aspire.Hosting.IncrementalMigration\AspireConstants.Shared.cs" Link="AspireConstants.Shared.cs" />
  </ItemGroup>
</Project>
